version: '3.4'

volumes:
  storage:

services:
  chris:
    build:
      context: ../this-Cunningham-service
      dockerfile: ./Dockerfile
    depends_on:
      - 'database'
    links:
      - 'database'
    ports:
      - '3001:3001'

  saba:
    build:
      context: ../sabateklu-service
      dockerfile: ./Dockerfile
    depends_on:
      - 'database'
    links:
      - 'database'
    ports:
      - '8080:8080'

  thomas:
    build:
      context: ../thomas-mcnutt-service
      dockerfile: ./Dockerfile
    depends_on:
      - 'database'
    links:
      - 'database'
    ports:
      - '3003:3003'

  collin:
    build:
      context: ../collin-newman-service
      dockerfile: ./Dockerfile
    depends_on:
      - 'database'
    links:
      - 'database'
    ports:
      - '3000:3000'

  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - 'database'
    links:
      - 'database'
    ports:
      - '80:3004'

  database:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - 'storage:/data/db'
